# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Find author
      run: echo "Authors is ${{ github.actor }}"
    - name: Clone1
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete1
      run: |
         rm -r "Altify-Developing-Main"
    - name: Clone2
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete3
      run: |
         rm -r "Altify-Developing-Main"
    - name: Clone3
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete3
      run: |
         rm -r "Altify-Developing-Main"
    - name: Clone4
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete4
      run: |
         rm -r "Altify-Developing-Main"
    - name: Clone5
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete5
      run: |
         rm -r "Altify-Developing-Main"
    - name: Clone6
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete6
      run: |
         rm -r "Altify-Developing-Main"
    - name: Clone7
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete7
      run: |
         rm -r "Altify-Developing-Main"
    - name: Clone8
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete8
      run: |
         rm -r "Altify-Developing-Main"
    - name: Clone9
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete9
      run: |
         rm -r "Altify-Developing-Main"
    - name: Clone10
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete10
      run: |
         rm -r "Altify-Developing-Main"
